# -*- coding: utf-8 -*-
"""Ciel and Receipt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHOg7_LgSgypsPiguaKu-bhf_UrG9MPy
"""

T = int(input())

for i in range(T):
  b = int(input())
  j = int(b/2048)
  b = int(b%2048)
  while b!=0:
    j=int(j+b%2)
    b= int(b/2)
  print(j)