# -*- coding: utf-8 -*-
"""Small Factorials.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHOg7_LgSgypsPiguaKu-bhf_UrG9MPy
"""

T = int(input())

for i in range(T):
  num = int(input())
  factorial = 1
  if num == 0:
    print(factorial)
  else:
    for i in range(1,num + 1):
      factorial = factorial*i
    print(factorial)