# -*- coding: utf-8 -*-
"""Total Expenses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHOg7_LgSgypsPiguaKu-bhf_UrG9MPy
"""

T = int(input())

for i in range(T):
  result = 0
  quantity, price = map(int, input().split())
  if quantity>1000:
    result = (quantity*price)-0.1*(quantity*price)
  else:
    result = quantity*price
  print("%.6f"%(result))