# -*- coding: utf-8 -*-
"""Candies and Two Sisters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ti_EWZO3c6BAQLmp-f5cIJB6XcmDHhRZ
"""

t = int(input())
for i in range(t):
  n = int(input())
  if n==0 or n==1:
    print(0)
  else:
    print(int((n-1)/2))