# -*- coding: utf-8 -*-
"""Choosing Teams.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ti_EWZO3c6BAQLmp-f5cIJB6XcmDHhRZ
"""

n, k = map(int, input().split())
a = list(map(int, input().split()))
cnt = 0

for i in range(n):
  if a[i]+k<=5:
    cnt = cnt+1

print(int(cnt/3))