# -*- coding: utf-8 -*-
"""Divisibility Problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ti_EWZO3c6BAQLmp-f5cIJB6XcmDHhRZ
"""

n = int(input())

for i in range(n):
  a, b = map(int, input().split())
  cnt = 0
  if a%b==0:
    print(0)
  else:
    print(b-(a%b))