# -*- coding: utf-8 -*-
"""George and Accomodation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ti_EWZO3c6BAQLmp-f5cIJB6XcmDHhRZ
"""

n = int(input())
cnt = 0

for i in range(n):
  a, b = map(int,input().split())

  if b-a>=2:
    cnt = cnt+1

print(cnt)