# -*- coding: utf-8 -*-
"""HQ9+.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izQimESIJu2YTP10UjQfNYnzTZdmvCT7
"""

s = input()

if 'H' in s or 'Q' in s or '9' in s:
  print('YES')
else:
  print('NO')