# -*- coding: utf-8 -*-
"""Is your horseshoe on the other hoof?.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ti_EWZO3c6BAQLmp-f5cIJB6XcmDHhRZ
"""

cnt = 0
hoof = []
s1, s2, s3, s4 = map(int, input().split())

hoof.append(s1)
hoof.append(s2)
hoof.append(s3)
hoof.append(s4)

hoof.sort()

for i in range(3):
  if hoof[i]==hoof[i+1]:
    cnt = cnt+1

print(cnt)