# -*- coding: utf-8 -*-
"""Magnets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ti_EWZO3c6BAQLmp-f5cIJB6XcmDHhRZ
"""

n = int(input())
a = []
cnt = 1

for i in range(n):
  ele = int(input())
  a.append(ele)

for i in range(n-1):
  if a[i]!=a[i+1]:
    cnt=cnt+1

print(cnt)