# -*- coding: utf-8 -*-
"""Mishka and Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ti_EWZO3c6BAQLmp-f5cIJB6XcmDHhRZ
"""

n = int(input())
cnt1 = 0
cnt2 = 0

for i in range(n):
  a, b = map(int, input().split())
  if a>b:
    cnt1 = cnt1+1
  elif a<b:
    cnt2 = cnt2+1

if cnt1>cnt2:
  print("Mishka") 
elif cnt1<cnt2:
  print("Chris")
else:
  print("Friendship is magic!^^")