# -*- coding: utf-8 -*-
"""Next Round.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X2RuT_szUFBCU1rJT06qkdThIwPlTwkJ
"""

n, k = map(int, input().split())
counter = 0
a = input().split()

for i in range(n):
    if int(a[i]) >= int(a[k-1]) and int(a[i]) != 0:
        counter = counter + 1

print(counter)