# -*- coding: utf-8 -*-
"""Theatre Square.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DJjY5KQY34UItRkl-SXkKUrThh1k81xW
"""

m, n, a = map(int,input(). split())
x = m/a
y = n/a
if m % a != 0:
    x = x + 1
if n % a != 0:
    y = y + 1
x = int(x)
y = int(y)
print(x*y)