# -*- coding: utf-8 -*-
"""Tram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izQimESIJu2YTP10UjQfNYnzTZdmvCT7
"""

n = int(input())
a = []
b = []
for i in range(n):
  ele1, ele2 = map(int,input().split())
  a.append(ele1)
  b.append(ele2)

k = a[0]
maximum = 0

for i in range(n):
  ans = b[i] - a[i] + k
  k = ans
  if ans>maximum:
    maximum = ans

print(maximum)