# -*- coding: utf-8 -*-
"""Way Too Long Word.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y7W1wEsFSu-_wyDYkGiV5RoHdjFKPnW-
"""

T = int(input())
for i in range(T):
  st = input()
  if len(st)>10:
    print(f"{st[0]}{len(st)-2}{st[len(st)-1]}")
  else:
    print(st)

