# -*- coding: utf-8 -*-
"""Word.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1izQimESIJu2YTP10UjQfNYnzTZdmvCT7
"""

s = input()
lowercnt = 0
uppercnt = 0

for char in s:
  if char.isupper():
    uppercnt = uppercnt+1
  else:
    lowercnt = lowercnt+1

if uppercnt>lowercnt:
  s = s.upper()
else:
  s = s.lower()

print(s)