# -*- coding: utf-8 -*-
"""Is Prime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ghynTryTE4-hljCYbB9RJ05_cEEd9m3
"""

n = int(input())
flag = False
if n>1:
  for i in range(2,n):
    if n%i==0:
      flag = True
      break

if flag:
  print("No")
else:
  print("Yes")